### ISSUE TITLE
Extra records created

### ISSUE THREAD

**Issue by gbroiles** [kedarvj/mysql-random-data-generator#15]
This series of commands demonstrates the problem:

    echo "create database testdb;" > test.sql
    echo "use testdb;" >> test.sql
    wget -nv  https://raw.githubusercontent.com/kedarvj/mysql-random-data-generator/master/populate.sql
    cat populate.sql >> test.sql
    echo "create table mytable(text varchar(10), number float(10,2), mydate date);" >> test.sql
    echo "call populate('testdb','mytable',100000,'n');" >> test.sql
    echo "select count(*) from mytable;" >> test.sql
    mysql < test.sql

Output will be:

    Developed by
    Kedar Vaijanapurkar
    count(*)
    100199

The problem appears where the number of records generated is > 999 and appears to grow as the number of records requested grows.

**Comment by kedarvj** [comment]
That's because we're doing bulk inserts and number of dummy records is not a big deal. You can be off by the chunk size and that'd be approx 500 records max. This can be improved by doing 1 record at a time insertion or in advance calculating no.of rec required / chunksize to create the loop and then adding remaining records in smaller chunk.
That said, this is dummy or test data and having a few hundred extra records won't create any issue and hence i did not put extra effort to put this logic. Feel free create a PR. Thank you.
